"""empty message

Revision ID: 4b9bc9f59ad7
Revises: 
Create Date: 2020-11-01 03:15:47.909057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b9bc9f59ad7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_url', sa.String(length=64), nullable=True),
    sa.Column('asin', sa.String(length=64), nullable=True),
    sa.Column('review_rating', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.String(length=64), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('sell_price', sa.String(length=64), nullable=True),
    sa.Column('link', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asins_created_at'), 'asins', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asins_created_at'), table_name='asins')
    op.drop_table('asins')
    # ### end Alembic commands ###
