"""empty message

Revision ID: 4f357c4fa151
Revises: 9a81ae94dfce
Create Date: 2020-11-01 04:29:58.842808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4f357c4fa151'
down_revision = '9a81ae94dfce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_testasins_created_at', table_name='testasins')
    op.drop_table('testasins')
    op.drop_index('ix_gg_created_at', table_name='gg')
    op.drop_table('gg')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gg',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('site_url', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('asin', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_gg_created_at', 'gg', ['created_at'], unique=False)
    op.create_table('testasins',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('site_url', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('asin', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('review_rating', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('quantity', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('unit', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('sell_price', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('link', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_testasins_created_at', 'testasins', ['created_at'], unique=False)
    # ### end Alembic commands ###
