"""empty message

Revision ID: 641ca1306202
Revises: 
Create Date: 2020-11-05 01:41:49.092927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641ca1306202'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_url', sa.String(length=64), nullable=True),
    sa.Column('asin', sa.String(length=64), nullable=True),
    sa.Column('review_rating', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.String(length=64), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('sell_price', sa.String(length=64), nullable=True),
    sa.Column('link', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asins')
    # ### end Alembic commands ###
