"""empty message

Revision ID: c3c31f65a017
Revises: 4b9bc9f59ad7
Create Date: 2020-11-01 04:01:29.068747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3c31f65a017'
down_revision = '4b9bc9f59ad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testasins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_url', sa.String(length=64), nullable=True),
    sa.Column('asin', sa.String(length=64), nullable=True),
    sa.Column('review_rating', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.String(length=64), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('sell_price', sa.String(length=64), nullable=True),
    sa.Column('link', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_testasins_created_at'), 'testasins', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_testasins_created_at'), table_name='testasins')
    op.drop_table('testasins')
    # ### end Alembic commands ###
